apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ceph
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: ceph.hit.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rook-ceph-mgr-dashboard
            port: 
              number: 8443
