# example-csi-snapshot.yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: test-snapshot-pvc
spec:
  volumeSnapshotClassName: rook-ceph-block
  source:
    persistentVolumeClaimName: test-vol
